# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a08ea8f60487001c5975af2c84073f3c"
name = "Sticky-Cart-Bar"
handle = "sticky-cart-bar"
application_url = "https://says-ripe-oc-planned.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "storeapp-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://says-ripe-oc-planned.trycloudflare.com/auth/callback",
  "https://says-ripe-oc-planned.trycloudflare.com/auth/shopify/callback",
  "https://says-ripe-oc-planned.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
